models:
  Models\Service:
    name: string:191
    description: string:191
    price: decimal:10,2

controllers:
  Admin\Service:
    index:
      query: all
      render: admin.services.index with:services

    create:
      render: admin.services.create with:service

    store:
      validate: name, email, password
      save: service
      redirect: admin.services.index

    show:
      render: admin.services.show with:service

    edit:
      render: admin.services.edit with:service

    update:
      validate: name, email, password
      save: service
      redirect: admin.services.index

    destroy:
      delete: service
